name: build
on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    container: devkitpro/devkita64:latest
    steps:
    - uses: actions/checkout@master
      with:
        submodules: recursive
    - name: Build
      run: ./build.sh
